Workflows update.

diff --git a/.github/workflows/release-preview.yml b/.github/workflows/release-preview.yml
--- a/.github/workflows/release-preview.yml
+++ b/.github/workflows/release-preview.yml
@@ -2,7 +2,7 @@ name: Release Preview
 
 on:
   workflow_dispatch:
-  
+
   push:
     branches:
       - master
@@ -12,7 +12,7 @@ on:
       - preview
     branches:
       - master
-      
+
   delete:
     tags-ignore:
       - preview
@@ -30,14 +30,14 @@ jobs:
           delete_release: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          
+
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
           submodules: "recursive"
-          
-      - name: Tag Custom build with current commit SHA
+
+      - name: Tag with current commit SHA
         id: custom_build
         run: node.exe .github/workflows/tag-custom-build.js
 
@@ -48,10 +48,10 @@ jobs:
           for /F %%i in ('git describe --tags --abbrev^=0') do (set tag=%%i)
           if "%tag%"=="" (echo ::error::Last tag not found!& exit 1)
           if "%tag%"=="preview" (for /F %%i in ('git describe --tags --abbrev^=0 preview^^^^') do set tag=%%i)
-          
+
           rem Check for commits since the tag
           for /F %%i in ('git rev-list %tag%..HEAD') do (set commit=%%i)
-          
+
           if "%commit%"=="" (
             echo ::notice::No changes since last release found.
           ) else (
@@ -67,30 +67,36 @@ jobs:
             echo   [View commits]^(${{ github.server_url }}/${{ github.repository }}/compare/%tag%...preview^)>>preview_changes.md
             echo;>>preview_changes.md
             echo ^</details^>>>preview_changes.md
+            type preview_changes.md
           )
-          
-      - uses: actions/setup-node@v4
-        if: ${{ hashFiles('preview_changes.md') != '' }}
-        with:
-          node-version: lts/*
-        
-      - name: Configure msbuild
+
+      - name: Set up MsBuild
         uses: microsoft/setup-msbuild@v2
-        
+
       - name: Build CLEO Core
         if: ${{ hashFiles('preview_changes.md') != '' }}
         shell: cmd
         run: |
+          @echo off
           set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
-          msbuild -m CLEO5.sln /property:Configuration=Release /property:Platform=GTASA
-          
+          msbuild CLEO5.sln /property:Configuration=Release /property:Platform=GTASA /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
+          powershell -Command "(gc output.log) | sort | get-unique > output.log"
+          powershell -Command "(gc output.log) -replace '     \d>','' -replace '.:\\a\\plugin-sdk\\plugin-sdk\\','' | Out-File -encoding ASCII output.log"
+          powershell -Command "foreach($line in Get-Content 'output.log') { $m = $line -match '^(.*)\((\d+),(\d+)\): (\w+) (.*) \[.*\]$'; if ($m) {$m = $Matches; echo ('::'+$m[4]+' file='+$m[1]+',line='+$m[2]+',title=Core compilation::'+$m[5])} else {echo ('::error title=Core compilation::' + $line)} }"
+          for %%R in (output.log) do if not %%~zR lss 1 (exit 1)
+
       - name: Build CLEO Plugins
         if: ${{ hashFiles('preview_changes.md') != '' }}
         shell: cmd
         run: |
+          @echo off
           set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
-          msbuild -m cleo_plugins/CLEO_Plugins.sln /property:Configuration=Release /property:Platform=x86
-          
+          msbuild cleo_plugins/CLEO_Plugins.sln /property:Configuration=Release /property:Platform=x86 /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
+          powershell -Command "(gc output.log) | sort | get-unique > output.log"
+          powershell -Command "(gc output.log) -replace '     \d>','' -replace '.:\\a\\plugin-sdk\\plugin-sdk\\','' | Out-File -encoding ASCII output.log"
+          powershell -Command "foreach($line in Get-Content 'output.log') { $m = $line -match '^(.*)\((\d+),(\d+)\): (\w+) (.*) \[.*\]$'; if ($m) {$m = $Matches; echo ('::'+$m[4]+' file='+$m[1]+',line='+$m[2]+',title=Plugins compilation::'+$m[5])} else {echo ('::error title=Plugins compilation::' + $line)} }"
+          for %%R in (output.log) do if not %%~zR lss 1 (exit 1)
+
       - name: Gather output files
         if: ${{ hashFiles('preview_changes.md') != '' }}
         id: prepare_archive
@@ -110,7 +116,7 @@ jobs:
 
           @echo Download Sanny Builder Library json
           curl https://raw.githubusercontent.com/sannybuilder/library/master/sa/sa.json -o .output\Release\cleo\.config\sa.json
-          
+
       - name: Pack archive
         if: ${{ hashFiles('preview_changes.md') != '' }}
         uses: thedoctor0/zip-release@0.7.6
@@ -120,7 +126,7 @@ jobs:
           directory: '.output/Release'
           exclusions: '*.pdb *.exp *.lib'
           custom: '-mm=Deflate -mfb=258 -mpass=15'
-          
+
       - name: Create 'preview' release
         if: ${{ hashFiles('preview_changes.md') != '' }}
         uses: ncipollo/release-action@main
