Updates

diff --git a/.github/workflows/release-preview.yml b/.github/workflows/release-preview.yml
--- a/.github/workflows/release-preview.yml
+++ b/.github/workflows/release-preview.yml
@@ -67,29 +67,35 @@ jobs:
             echo   [View commits]^(${{ github.server_url }}/${{ github.repository }}/compare/%tag%...preview^)>>preview_changes.md
             echo;>>preview_changes.md
             echo ^</details^>>>preview_changes.md
+            type preview_changes.md
           )
-          
-      - uses: actions/setup-node@v4
-        if: ${{ hashFiles('preview_changes.md') != '' }}
-        with:
-          node-version: lts/*
         
-      - name: Configure msbuild
+      - name: Set up MsBuild
         uses: microsoft/setup-msbuild@v2
         
       - name: Build CLEO Core
         if: ${{ hashFiles('preview_changes.md') != '' }}
         shell: cmd
         run: |
+          @echo off
           set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
-          msbuild -m CLEO5.sln /property:Configuration=Release /property:Platform=GTASA
+          msbuild CLEO5.sln /property:Configuration=Release /property:Platform=GTASA /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
+          powershell -Command "(gc output.log) | sort | get-unique > output.log"
+          powershell -Command "(gc output.log) -replace '     \d>','' -replace '.:\\a\\plugin-sdk\\plugin-sdk\\','' | Out-File -encoding ASCII output.log"
+          powershell -Command "foreach($line in Get-Content 'output.log') { $m = $line -match '^(.*)\((\d+),(\d+)\): (\w+) (.*) \[.*\]$'; if ($m) {$m = $Matches; echo ('::'+$m[4]+' file='+$m[1]+',line='+$m[2]+',title=Core compilation::'+$m[5])} else {echo ('::error title=Core compilation::' + $line)} }"
+          for %%R in (output.log) do if not %%~zR lss 1 (exit 1)
           
       - name: Build CLEO Plugins
         if: ${{ hashFiles('preview_changes.md') != '' }}
         shell: cmd
         run: |
+          @echo off
           set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
-          msbuild -m cleo_plugins/CLEO_Plugins.sln /property:Configuration=Release /property:Platform=x86
+          msbuild cleo_plugins/CLEO_Plugins.sln /property:Configuration=Release /property:Platform=x86 /m /fileLogger1 /fileLoggerParameters1:warningsOnly;errorsOnly;logfile=output.log
+          powershell -Command "(gc output.log) | sort | get-unique > output.log"
+          powershell -Command "(gc output.log) -replace '     \d>','' -replace '.:\\a\\plugin-sdk\\plugin-sdk\\','' | Out-File -encoding ASCII output.log"
+          powershell -Command "foreach($line in Get-Content 'output.log') { $m = $line -match '^(.*)\((\d+),(\d+)\): (\w+) (.*) \[.*\]$'; if ($m) {$m = $Matches; echo ('::'+$m[4]+' file='+$m[1]+',line='+$m[2]+',title=Plugins compilation::'+$m[5])} else {echo ('::error title=Plugins compilation::' + $line)} }"
+          for %%R in (output.log) do if not %%~zR lss 1 (exit 1)
           
       - name: Gather output files
         if: ${{ hashFiles('preview_changes.md') != '' }}
